### ISSUE TITLE
Add a bit of CI for the project

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-server#103]
Currently when we are pushing something in the master branch we do not perform any checks at all and sometimes our containers are broken after commits which seemed to be pretty safe. Like that case when updating a minor version of the `osprey` package screwed everything up.

I was wondering if there is a way of running `docker-compose up` in Travis CI and checking at least that `localhost:8055` gives you a `200`.

**Comment by donaldwasserman** [comment]
This could be accomplished by running a simple mocha test to do the above
