### ISSUE TITLE
Clarify inventory fields

### ISSUE THREAD

**Issue by drakemedic** [HospitalRun/hospitalrun-server#105]
I have been looking at the inventory import function and need some clarification.
How do we handle the situation where the distribution unit is a box of e.g. 50 items,and we have a quantity of 300 items?
Should we add the number of items per box with the name and then quantity as the number of boxes?

Also, if items have a size, should that be appended to the name or is it possible to add more terms to the schema?

I'd be willing to have a go at modifying this if appropriate.

**Comment by tangollama** [comment]
Paul,

If you're consuming them (i.e. considering them "used" with regards to
stock mgmt or costing) one box at a time, it sounds like you have 6 units.
If you use them one at a time, then you'd register them as 300 units.

As for the second question - at present - that's multiple items that each
happen to have a different size. Feel free to submit a PR if you'd like to
see that changed.
