### ISSUE TITLE
error gething Your session has expired. Please login to continue. on adding new users 

### ISSUE THREAD

**Issue by qasmaoui** [HospitalRun/hospitalrun-server#107]
Hello , i managed to install hospital-server buth each time i want to add new user i get the error 
Your session has expired. Please login to continue.
is this noraml !

**Comment by donaldwasserman** [comment]
@qasmaoui Sorry we haven't gotten back, if this is still an issue, comment here adn we'll reopen!

**Comment by habibhermes** [comment]
@qasmaoui Hi, have you been able to solve the issue? I am currently having the same issue.

**Comment by GidyCazaus** [comment]
i Have same issue. please help
