### ISSUE TITLE
API External Submission

### ISSUE THREAD

**Issue by bkerensa** [HospitalRun/hospitalrun-server#11]
Allow third-party apps like Glucosio to submit glucose and other health metrics

**Comment by tangollama** [comment]
@bkerensa I'm 100% for building capacity for integrating with API's like this. Do you have any specific guidance on a first concrete step?

**Comment by tangollama** [comment]
@bkerensa any interest in defining some concrete calls / API's from systems like Glucosio? If we could get more definition here, it would make it more likely a feature like this could / would be added.

**Comment by bkerensa** [comment]
Ideally for us to be willing to add support for HospitalRun what we would want to be able to do via API
is push any data users enter into Glucosio on demand.

So ideally we would want a way to allow user to authenticate to their record and push in that data
not entirely sure what this would look like on your side.

Do you have any doc for your api so I can dig in?

**Comment by drpump** [comment]
Regarding APIs, I would suggest implementing an API based on the draft [FHIR ](https://www.hl7.org/fhir/) standard. The community around it is very active and progressive, and OAUTH is also their preferred authentication/authorisation mechanism. 

For submitting metrics, the FHIR [Observation ](https://www.hl7.org/fhir/observation.html) resource is likely to be most appropriate.

**Comment by bkerensa** [comment]
That would work for us as we look at adding this kind of support and the closer to a standard we can get external API's to work the better for us.

**Comment by mariusa** [comment]
Is there any API to get data in/out of hospitalrun server that other apps could use?
examples: create patient, read patient details
Couldn't find any docs. Thanks

**Comment by tangollama** [comment]
@mariusa there is not presently an API. That would certainly be a welcome addition to the server project if you or someone was interested in investing the time to build it. Presently, the project is generally focused on features and functions; but - as it's an OSS project - that can change with community input / energy.

**Comment by fox1t** [comment]
This kind of integrations will be handled by HL7 module.
