### ISSUE TITLE
Error: docker-compose up --build -d

### ISSUE THREAD

**Issue by sarzali07** [HospitalRun/hospitalrun-server#118]
After executing docker-compose up --build -d

Error comes

Pulling couchdb (couchdb:1.7.1)...
Pulling repository docker.io/library/couchdb
ERROR: Tag 1.7.1 not found in repository docker.io/library/couchdb

Regards

**Comment by stukalin** [comment]
@sarzali07 that's strange. I've just pulled the image under the question. Probably you have some issues with docker itself. Could https://github.com/docker/distribution/issues/1947 or https://github.com/moby/moby/issues/26295 be any of help?

**Comment by sarzali07** [comment]
docker info             Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.6-cs13
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.945 GiB
Name: sarfaraz-virtual-machine
ID: MHMQ:5JQP:UBGB:VI4M:NSKZ:25SJ:EOGR:RWHW:MWPP:FLOI:3QQH:GWEP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8


docker version          Client:
 Version:      1.12.6-cs13
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   0ee24d4
 Built:        Mon Jul 24 18:09:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6-cs13
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   0ee24d4
 Built:        Mon Jul 24 18:09:19 2017
 OS/Arch:      linux/amd64


Kindly let me know whats wrong

**Comment by sarzali07** [comment]
I have ubuntu 14.04,
If possible send me command lines to install hospital run on local environment.

Regards

**Comment by sarzali07** [comment]
git clone git@github.com:HospitalRun/hospitalrun-server.git
Cloning into 'hospitalrun-server'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by donaldwasserman** [comment]
@sarzali07 That's weird - that should never happen. This is a publically available repo.

I think you need to follow the instructions here: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

I suspect there is an issue with your git user on your machine.

**Comment by sarzali07** [comment]
After all searching and modification Now I receive

docker-compose up --build -d
Pulling couchdb (couchdb:1.7.1)...
1.7.1: Pulling from library/couchdb
1c7fe136a31e: Pull complete
7d264534fc3c: Pull complete
d19f72163506: Pull complete
457a2d7a5f09: Pull complete
1adbe2b627b6: Pull complete
2142729480fe: Pull complete
023a3dfd2353: Pull complete
Digest: sha256:40554e2d5a54dbd588fdb6328c9e2b0a9f4dad4b030f5c6501b2e288fc32c1f8
Status: Downloaded newer image for couchdb:1.7.1
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:5.3.1)...
ERROR: Get https://docker.elastic.co/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by sarzali07** [comment]
Finally I manage to install 


Successfully built 5fd1b68d96b9
Successfully tagged hospitalrun_nginx:latest
elasticsearch_hr is up-to-date
couchdb_hr is up-to-date
logstash_hr is up-to-date
Starting hospitalrun ... done
hospitalrunserver_nginx_1 is up-to-date


But when I type localhost it give UNABLE TO CONNECT INTERNET ERROR

**Comment by wbuarque** [comment]
Hi @sarzali07 do you managed to connect? 
I'm facing same problem here: Unable to Connect

**Comment by MatthewDorner** [comment]
If you run `docker ps -a` when having this problem, do all 5 containers show up as running?

If your nginx container is shutting down it may be because of not setting up the SSL configuration. See the instructions in https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md.

**Comment by sarzali07** [comment]
@wbuarque I left this management system. very complex and not easy to manage by one person.

**Comment by wbuarque** [comment]
Hi Matthew,

yes, exception is elasticsearch_hr, but is my server setup witch has lower memory. My SSL env is `none`.
Doing a `curl -X GET http://127.0.0.1` give me an 302 page.
