### ISSUE TITLE
Add Configurable Frontend Install Option

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-server#122]
The current deployment setup uses the built assets in the `hospitalrun-frontend/public` folder. For many different reasons (testing, demos, build-specific options, etc) we should probably have a configuration to allow the server to build the ember app at install time, rather than pulling in a entire compiled version (although that should be the default). 

### Acceptance Critera

* The default option of using the `public` folders should be the default 
* Site installers should have the ability to build from a specific tag/branch in github
* Site installers should have the abiltiy to pass in some reasonable set of build-time configuration options (limiting translations, browser support, etc)

**Comment by stukalin** [comment]
Didn't quite understand why?

**Comment by donaldwasserman** [comment]
@stukalin I added some more details if that makes more sense
