### ISSUE TITLE
Running npm start in server

### ISSUE THREAD

**Issue by akash65** [HospitalRun/hospitalrun-server#128]
while running npm start commad inside hospital repo directory haveing error says no module found "yarn install".can anyone help me?

**Comment by hpierce1102** [comment]
Could you provide more info? I'm trying to install and run for the first time too and am not running into this one. 

What you're describing sounds like `Error: Cannot find module 'yarn install'`. But I'm skeptical of that being the problem. Could you copy and paste the error verbatim here?

**Comment by donaldwasserman** [comment]
@akash65 This sounds like you're to start development on the frontend. You need to use https://github.com/HospitalRun/hospitalrun-frontend
