### ISSUE TITLE
"/bin/sh: 1: certbot-auto: not found" when running docker-compose up --build

### ISSUE THREAD

**Issue by hpierce1102** [HospitalRun/hospitalrun-server#129]
I'm trying to build the app locally for development purposes and am struggling to do so. I'm following the instructions in the [deployment guide](https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md#step-by-step-guide), but when I run `docker-compose up --build` the nginx container fails to build, providing this error:

```
/bin/sh: 1: certbot-auto: not found
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c certbot-auto --os-packages-only --non-interactive' returned a non-zero code: 127
```

My docker host is Windows 10 (against the stated assumption of Ubuntu 14.04).

How do I get around this? If this isn't the best way to get a development environment working, is there a better alternative?

**Comment by MatthewDorner** [comment]
If you want to develop on the frontend, where the main part of the application is, just clone and run the hospitalrun-frontend repository by itself.

You won't be able to develop on the frontend if you install hospitalrun-server, since it just gets the frontend as an npm package.

**Comment by hpierce1102** [comment]
Understood - my intention is to see if I can do anything to work out some outstanding [issues labeled with CI/CD ](https://github.com/HospitalRun/hospitalrun-server/issues?q=is%3Aopen+is%3Aissue+label%3ACI%2FCD)on this repository. While it might not be strictly necessary, I think it would be a Good Thing™ to have it running locally before spending any time trying to automate deploying/test/whatever to it.

**Comment by MatthewDorner** [comment]
OK. I've always used Ubuntu in a VM to run the server, so you could try that. But I'll set up Windows 10 and see if I have the same problem.

**Comment by MatthewDorner** [comment]
Tested on Win10, had the same problem as you. Went away after I set:

git config --global core.autocrlf false

and then deleted and cloned the repo again so it has the correct line endings. And then everything else appears to work.
