### ISSUE TITLE
db structure

### ISSUE THREAD

**Issue by bhx98** [HospitalRun/hospitalrun-server#133]
Dears, I would appreciate for any help
I want to Analysis HospitalRun DB Structure in couchdb before using it
but even after inserting some test record i couldn't find any related data in couchdb(main and config db) 
not in Hospital Server edition 
not with hospitalrun win application

**Comment by donaldwasserman** [comment]
@bhx98 Happy to help with this, i think you're best bet is to hop onto slack and ask your question there!
