### ISSUE TITLE
Add option of auto billing

### ISSUE THREAD

**Issue by sthaiya** [HospitalRun/hospitalrun-server#134]
There is need to auto bill clients and have them pay before service. For instance immediately a Visit is started for a client then we can auto bill them

**Comment by chaitanya-y** [comment]
hii sthaiya,
i am trying to create patient list but i am getting unauthorized you are not authorized to access this db how tom fix this?

**Comment by p-mcgowan** [comment]
@chaitanya-y your issue is unrelated (see [your actual issue](https://github.com/HospitalRun/hospitalrun-server/issues/139)) - try to keep conversations within issues to the actual stated issue
