### ISSUE TITLE
Unable to downgrade from couchdb 2.x to 1.6.1

### ISSUE THREAD

**Issue by shivaprashanthg** [HospitalRun/hospitalrun-server#137]
Unable to downgrade from couchdb 2.x to 1.6.1  on ubuntu18.04, any help.

**Comment by chaitanya-y** [comment]
hii shiva,
i am trying to create patient list but i am getting unauthorized you are not authorized to access this db how tom fix this?

**Comment by p-mcgowan** [comment]
@chaitanya-y your issue is unrelated (see [your actual issue](https://github.com/HospitalRun/hospitalrun-server/issues/139)) - try to keep conversations within issues to the actual stated issue
