### ISSUE TITLE
security issue - Not able to save data to database{"error":"unauthorized","reason":"You are not authorized to access this db."}

### ISSUE THREAD

**Issue by chaitanya-y** [HospitalRun/hospitalrun-server#139]
I  am not able to save data in main database. I created security document also. 
{"error":"unauthorized","reason":"You are not authorized to access this db."}
how to fix this?

**Comment by p-mcgowan** [comment]
https://github.com/HospitalRun/hospitalrun-server#alternative-installation step 5.iv might solve it
