### ISSUE TITLE
creating new user and users options not working - couchdb 2.3.0 how to fix this?

### ISSUE THREAD

**Issue by chaitanya-y** [HospitalRun/hospitalrun-server#140]
creating "New User" and "Users" options not working. I am using hospitalrun-server for UI and couchdb 2.3.0 version . I am getting error as one popup coming saying your session is expired please login to continue.How to fix this?
share your solutions and some ideas atleast how to fix this to 2.3.0?
with 1.6.1 it is working fine but I want to use latest couchdb version 2.3.0.

**Comment by MatthewDorner** [comment]
I think it's the same issue as https://github.com/HospitalRun/hospitalrun-frontend/issues/953.
