### ISSUE TITLE
Any better install instructions?

### ISSUE THREAD

**Issue by penguin8r** [HospitalRun/hospitalrun-server#144]
Docker install doesn't work.  It's apparently looking for some old Debian repositories that are not available anymore:
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

Alternate install instructions are incomplete.
Is this project still active?

**Comment by mpszambia** [comment]
Hi, Try and place these lines of code in your DockerFile after ARG SSL_TYPE:

```
#Add these three lines of code to work around moved files
RUN echo 'Acquire::Check-Valid-Until no;' > /etc/apt/apt.conf.d/99no-check-valid-until
RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
```
You will find the discussion on what the last two lines are doing [here](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository): 

And then you will find the first line explanation [here](https://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror):

Read them in that order as the first piece describes the real problem and solution. The latter is the icing on the cake :-).


It took me about 5 hours today to work all that out!! Still having other problems, but at least it builds to a point. Good luck.

**Comment by penguin8r** [comment]
there is no ARG SSL_TYPE line in the current Dockerfile. :(
There is a reference to that in the 'docker-compose.yml, but I don't believe that the docker RUN statements belong in the .yml?  Or is that acceptable?
I would honestly rather just do manual install rather than rely on the house of cards that Docker creates, but I tried following those instructions too and it seems I failed to read sufficiently between the lines.  Would really like to see this thing run!

**Comment by MatthewDorner** [comment]
I think @mpszambia might mean to place those lines in the nginx/Dockerfile ?

https://stackanswers.net/questions/w-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-updates-main-binary-amd64-packages-404-not-found-ip-151-101-140-204-80
seems to be a recent change. Based on the above comment, is it a dependency of the nginx image? So maybe just need to update to a newer nginx image?

**Comment by penguin8r** [comment]
that's exactly what it was, those lines go specifically in the nginx/Dockerfile.  Thank you.
Still doesn't run properly or bind to the network, so I just get a default nginx page when I browse to the system IP, but I appreciate the help.  I was thinking this was browser accessible, didn't realize it needs a front end/fat client to work.

**Comment by MatthewDorner** [comment]
hmm, worked for me. You should use SSL_TYPE of "none" if you just want to set up a local test server, otherwise it's going to try running the LetsEncrypt cert generation script and fail. but that ought to cause the entire Nginx container to fail so you wouldn't get a default Nginx page...

**Comment by mpszambia** [comment]
Hi Matthew,

Where do we set the SSL_TYPE value? I’m just getting started with this platform and related technologies, a pointer would be great help.

 

Thanks.

 

-------------------------------------

Marcus K. Achiume Jr.

Mobile Payment Solutions Ltd.

759 Independence Avenue, Woodlands

Lusaka, Zambia

Mobile: +260.966.601.973

               +260.979.601.973

Office:  +260.211.269.973

www.mps.co.zm <http://www.mps.co.zm/>

**Comment by mpszambia** [comment]
@MatthewDorner , found where to set it up. Thanks.

**Comment by cupliz** [comment]
you can run hospitalrun itself without nginx, or you can set up your own nginx later. you just need to disable nginx container in `docker-compose.yml` and add a port to app container.
example: 

> services:
>   # nginx:
>   #   build:
>   #     args:
>   #       DOMAIN_NAME: www.example.com
>   #       SSL_TYPE: auto
>   #     context: nginx/.
>   #     dockerfile: Dockerfile
>   #   links:
>   #     - hospitalrun
>   #   ports:
>   #     - "80:80"
>   #     - "443:443"
>   #   image: hospitalrun_nginx
>   #   volumes:
>   #     - ./data/nginx/letsencrypt:/etc/letsencrypt
>   #     - ./data/nginx/cert:/etc/nginx/cert
> 
>   hospitalrun:
>     container_name: hospitalrun
>     build: .
>     image: hospitalrun
>     ports:
>       - "3000:3000"
>     links:
>       - couchdb
>       - elasticsearch
>       - logstash
>     depends_on:
>       - couchdb
>       - elasticsearch
>       - logstash
>     container_name: hospitalrun
