### ISSUE TITLE
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apt-get update --fix-missing && apt-get install -y cron' returned a non-zero code: 100

### ISSUE THREAD

**Issue by someonewithsomepower** [HospitalRun/hospitalrun-server#145]
When I run 'docker-compose up --build' it provides me 

'Service 'nginx' failed to build: The command '/bin/sh -c apt-get update --fix-missing && apt-get install -y cron' returned a non-zero code: 100'

My host is mac os 14.XX.

How do I solve that？

**Comment by thenikin** [comment]
same issue here. Tried with debian, ubuntu, nothing works

**Comment by professorhaseeb** [comment]
I got the same error!... any updates on this?

**Comment by sajid-r** [comment]
I solved it by changing the nginx version to nginx:1.15.12 in nginx/Dockerfile

**Comment by professorhaseeb** [comment]
i have already proposed a solution (#146 ) for this

**Comment by tehKapa** [comment]
Closed by #146.
