### ISSUE TITLE
Moving the existing reporting to the Node server backend

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-server#15]
The ticket was first logged here:  https://github.com/HospitalRun/hospitalrun-frontend/issues/204

The move could be fairly straightforward for a Node developer, because: Javascript. 

The concept here is that the frontend would now become more of a proxy to the node backend request vs. the system processing the business logic. To do that, the framework for making the call to an endpoint / endpoints on the server needs to be created and the report-generating logic from the following files needs to be moved from the frontend code base an appropriate place in the server codebase. That list is.
- [ ] https://github.com/HospitalRun/hospitalrun-frontend/tree/master/app/inventory/reports/controller.js
- [ ] https://github.com/HospitalRun/hospitalrun-frontend/tree/master/app/patients/reports/controller.js

Ideally the node endpoints would return the reports in the [JSON API](http://jsonapi.org/) format since that is the default for Ember Data.

**Comment by tangollama** [comment]
@jkleinsc can you review and confirm this?

**Comment by jkleinsc** [comment]
@tangollama I updated your comment to point to the specific files that currently contain the JS logic to build the reports.  Also, I noted we should try to return report results in the JSON API format since Ember Data uses that.
