### ISSUE TITLE
npm ERR! No valid versions available for hospitalrun

### ISSUE THREAD

**Issue by asyf** [HospitalRun/hospitalrun-server#150]
Not able to download hospitalrun dependency

**Comment by blestab** [comment]
Since this has been marked "wontfix", i guess due to the new version coming up, Is there an alternative way to installing the hospitalrun service correctly, that someone can share?

**Comment by tehKapa** [comment]
Sadly, at the moment the core team cannot deal with issues related to version 1.0.0-beta.

We don't have an ETA for version 2 yet.

**Comment by blestab** [comment]
Noted with thanks @tehKapa
