### ISSUE TITLE
Add coveralls

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-server#156]
## 🚀 Feature Proposal

Add coveralls. 

## Motivation

See how well the tests are doing.

**Comment by fox1t** [comment]
@tehKapa what we need to add this also to server?

**Comment by tehKapa** [comment]
I already added the Coveralls variable on Travis.
I think that's [enough](https://node-tap.org/docs/coverage/#travis-ci-and-coverallsio-integration). Do we use node-tap, right?

**Comment by tehKapa** [comment]
Something's wrong.

``` 
[error] "2019-10-15T15:35:13.714Z"  'error from lcovParse: ' 'Failed to parse string'
308[error] "2019-10-15T15:35:13.716Z"  'input: ' ''
309[error] "2019-10-15T15:35:13.717Z"  'error from convertLcovToCoveralls'
310
311/home/travis/build/HospitalRun/hospitalrun-server/node_modules/coveralls/bin/coveralls.js:18
312        throw err;
313        ^
314Failed to parse string
```

**Comment by tehKapa** [comment]
So, quickly recap:

- I've set environment variable COVERALLS_REPO_TOKEN on Travis
- Update [package.json](https://github.com/HospitalRun/hospitalrun-server/commit/c35b71be3ea87f45a6ba9462ce5ff1478ecbaf68) and [travis.yml](https://github.com/HospitalRun/hospitalrun-server/commit/3a8857536f83d35384815a7a4fefc1571d73bb13) but once they run the tests, they still don't show up on coveralls
