### ISSUE TITLE
Notify a physician when a lab is completed

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-server#16]
![hospitalrun lab notifications - new page 1](https://cloud.githubusercontent.com/assets/929261/15619859/e0b5c474-2424-11e6-9f22-b8846dcd0946.jpeg)
Notify the requesting physician when lab data is entered.

**Comment by richiethomas** [comment]
Hi, a few questions about this issue:

-How much of the functionality in the flowchart is already in place?
-To be clear, is it correct that this story just involves the last arrow in the flowchart (the one from `Save Lab` back to the clinician)?
-Am I correct that this requires work in both the hospitalrun-server and hospitalrun-frontend codebases?  i.e. server-side work will handle the message passing, and the front-end work will handle the message appearing in the clinician's UI?
