### ISSUE TITLE
Where is all the code?

### ISSUE THREAD

**Issue by paulogr** [HospitalRun/hospitalrun-server#177]
I'm probably missing something but where is all the code? 

I'm here to investigate the server code for learning purposes but I can't find anything.

The services and plugins folders has just some stub code.

Thanks for any help!

**Comment by fox1t** [comment]
Hi @paulogr! We are in complete rewrite process of the version 2.0.0. Right now the major work was done on frontend and components repositories. Soon I'll make first commits to this repo. Are you a Node.js developer? If so, join our slack for the last updates about this and other repos and roadmaps.

**Comment by paulogr** [comment]
Hi @fox1t thanks for your answer, yes I'm a node developer, new to Fastify and very excited to work with it.

How can I join the slack?

**Comment by fox1t** [comment]
I sent you an invite on your personal email.

**Comment by paulogr** [comment]
Great, thank you!

**Comment by fox1t** [comment]
You are welcome! :)
