### ISSUE TITLE
Build the basis for the notification framework

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-server#18]
There are numerous notification requirements / opportunities in the system; but the biggest need is to think through the framework for registering and delivering notifications. 

Notification types should at least begin with:
- Email
- A notifications interface on the home screen of HospitalRun

In the future, tying into a text messaging service or even a mobile version of the system could be supported. The point is that the framework needs to allow developers to easily register to listen for notifications surrounding a given object (or document) and then to deliver a series of notifications based on an event.

**Comment by titonobre** [comment]
Hi.
Today, at the Hack Day Lisbon, I started working in the notifications system based on some tips from @jkleinsc.

**Comment by tangollama** [comment]
Design doc for the Lisbon Hack Day https://docs.google.com/document/d/1tQzECDRgBkbvtMizsR-Prh0-fX_djivadFe_fK4eCW4/edit#heading=h.23y5yhjqf9dn

**Comment by titonobre** [comment]
After a conversation in Lisbon with @jkleinsc I went home thinking about the notifications system.

> Phase 1: Basic push native notifications
> Step 1 is to create a HospitalRun server (Node-based) framework/utility for registering and sending notifications using the native notification constructs in modern browsers, etc. These notifications do not persist and are surfaced purely to ensure that user work (actions needed in the system) are made apparent to a user (or set of users) in as close to real-time as possible.

The first step leads us right away to push notifications. Wouldn't be better to start with someting like the following?

# Step 1
Create dblisteners that listens for changes and send notifications to users/roles. These notitifications are stored in the DB.

# Step 2
Create a component to show the notifications for the current user.
Something like this:
![image](https://cloud.githubusercontent.com/assets/7109082/16228623/053b3e20-37b0-11e6-8608-06c3d102668c.png)

And maybe as a popup menu like this:
![image](https://cloud.githubusercontent.com/assets/7109082/16228553/a2decdaa-37af-11e6-9870-2a08af6c68bb.png)

# Step 3
Create a dblistener that listens for new notifications and dispatches them using the native notification constructs in modern browsers, SMS, e-mail or any other mean.

**Comment by sericaia** [comment]
@tangollama what do you think? can the designs be adjusted to this proposal?

**Comment by jkleinsc** [comment]
@sericaia sorry for my delay in responding.  I was away but I am back now.  I think the suggestion @titonobre is great and we should adjust the design to to accommodate.

**Comment by Selvaticus** [comment]
Hi All,

Is help still needed/wanted on this issue?

**Comment by tangollama** [comment]
Diago: in a few words - yes please.

**Comment by Selvaticus** [comment]
Hi All,

Tried to have a first stab at the problem and how the system "would" work. This will most likely change based on your feedback.

### Model

```json
{
  "SourceType": 0,
  "Source": "",
  "Persisted": false,
  "Target": "Dr. Who",
  "Title": "Imaging Results",
  "Message": "Please collect results from desk X"
}
```

- SourceType: Would describe the document originating the notification, this would allow for richer options on notification presentation
- Source: The origin document identification.
- Persisted: If the notification should be persisted or just attempted presentation and forgotten afterwards.
- Target: The User identification.
- Title: Small summary description
- Message: Notification messaging/description

### Db Listeners

Would decide depending on the DB Change what notification to sent, and if it should be sent for a `Role` would create all individual necessary `User` notifications.

PS: This should most likely change into a simple event creator and an extra aggregator should exist to create the notifications. (Again first stab at the problem.)

### Dispatcher

Dispatcher would deliver the notifications to the `User` based on:

- `User` preferences
- Available delivery venues (Email, SMS, App)
- Active status of the `User`, i.e. if the user is currently on-line in the app would be faster to send push notification to the browser than would be to send an email.


Please let me know your thoughts, hopefully now I will have some time to start working on it.

Cheers,
Diogo Silva
