### ISSUE TITLE
fastify-autoload prevents plugins being loaded correctly

### ISSUE THREAD

**Issue by fox1t** [HospitalRun/hospitalrun-server#236]
## 🐛 Bug Report

Discussion and issue here: https://github.com/fastify/fastify-autoload/issues/61
PR: https://github.com/fastify/fastify-autoload/pull/62

**Comment by tehKapa** [comment]
@fox1t they've accepted your PR

**Comment by fox1t** [comment]
Fixed on `fastiify-autoload` v 1.2.1
