### ISSUE TITLE
Hospitalrun not performing logins.

### ISSUE THREAD

**Issue by SheriefAlaa** [HospitalRun/hospitalrun-server#30]
Hi,

I installed CouchDB 1.6, hospital-run-server, ran npm install then npm start and this time I am on defaults and also following the setup guide to the letter. After logging in I see basically nothing and the only working event is the settings button (logout/about).

Database setup (http://localhost:5984/_utils/index.html):
```
[~/vagrant_trusty/hospitalrun-server] $ initcouch.sh
""
{"ok":true}
{"ok":true}
{"ok":true}
{"ok":true}
{"ok":true}
"{couch_httpd_oauth, oauth_authentication_handler}, {couch_httpd_auth, proxy_authentification_handler}, {couch_httpd_auth, cookie_authentication_handler}, {couch_httpd_auth, default_authentication_handler}"
"true"
{"ok":true,"id":"org.couchdb.user:hradmin","rev":"1-edefdea74a4de3c96f0764a90ed0b522"}
```

config.js:
```
var config = {
  couchDbServer: 'localhost',
  couchDbPort: '5984',
  couchDbUseSsl: false,
  couchDbChangesSince: 'now',
  couchAdminUser: 'COUCH ADMIN USER GOES HERE',
  couchAdminPassword: 'COUCH ADMIN PASSWORD GOES HERE',
  googleClientId: 'FOR GOOGLE SSO; GOOGLE CLIENT ID GOES HERE',
  googleClientSecret: 'FOR GOOGLE SSO; GOOGLE CLIENT SECRET GOES HERE',
  serverPort: '3000',
  server: 'localhost',
  sslCert: 'file location of ssl cert if needed',
  sslKey: 'file location of ssl key if needed',
  sslCA: [], // Array of file locations of trusted certificates in PEM format if needed
  useSSL: false,
  imagesdir: __dirname + '/patientimages',
  logRequests: false,
  logFormat: 'default', // See http://www.senchalabs.org/connect/logger.html for log formats
  useGoogleAuth: false,
  useCertBot: false
};
```

Screenshots of what happens when I click login:
```
https://www.dropbox.com/sh/vi4sea2fk87w8de/AAB9Ctw2lz7vVw8eo6bhq88Sa?dl=0
```

Thanks.

**Comment by jkleinsc** [comment]
@SheriefAlaa You need to replace the following in config.js:
  couchAdminUser: 'COUCH ADMIN USER GOES HERE',
  couchAdminPassword: 'COUCH ADMIN PASSWORD GOES HERE',

with the couch admin user and password.  If you just ran initcouch.sh with no arguements, the values should be:
  couchAdminUser: 'couchadmin',
  couchAdminPassword: 'test',

**Comment by SheriefAlaa** [comment]
@jkleinsc I forgot to mention that I tested with and without adding in a user 
(hradmin:test, I also just tested couchadmin:test) to config.js. The outcome is the same. Have you checked the screenshots (I added two more to the folder - CouchDB isn't even getting requests)?

**Comment by jkleinsc** [comment]
@SheriefAlaa a couple of things to investigate:
1) Do you see any output in the terminal where you are running hospitalrun (eg npm start)
2) Can you login into futon by going to http://127.0.0.1:5984/_utils/ and then clicking on login in the lower right hand corner?  You should be able to login with both couchadmin/test and hradmin/test
Once you login, verify that there is a config database and a main database.

Also, you can't login into HospitalRun using couchadmin/test.  You need to use hradmin/test.  Couchamdin/test is a couchdb only user and not intended for logging into HospitalRun.
