### ISSUE TITLE
Synk couldnt patch vulnerabilities

### ISSUE THREAD

**Issue by lucifer360** [HospitalRun/hospitalrun-server#33]
**_hospitalrun-server@0.9.17 Snyk couldn't patch the vulnerabilities because GNU's patch is not available. please install "patch" and try again_**

**Comment by emadehsan** [comment]
You are probably on windows. You can solve this in two ways:

1. Either install GNU's patch
or 
2. Install [Cygwin](https://cygwin.com/index.html) on windows and then run `npm install`

**Comment by jkleinsc** [comment]
Snyk is no longer running on npm install so this isn't an issue anymore.
