### ISSUE TITLE
Identify and document which versions of frontend are compatible with which versions of backend.

### ISSUE THREAD

**Issue by phanimahesh** [HospitalRun/hospitalrun-server#4]
In case backwards incompatible changes are introduced, for instance to resolve #3, there must not be any ambiguity about which version of backend and which version of frontend can be used together.

One way is to version the API, and document the api versions provided by backend and required by client. Semantic versioning guidelines can be used to increment version numbers when changes are introduced, and by looking at the versions of backend and frontend, one can easily determine if they are compatible.

**Comment by jglovier** [comment]
Also, we should really have a test suite setup for this.

**Comment by jkleinsc** [comment]
I would like to propose a simple solution to this:
1) As a baseline for versions, we should be using semver: http://semver.org/
2) I would like to follow the approach Ember is using for [Ember 2.x](http://emberjs.com/blog/2015/06/16/ember-project-at-2-0.html).  The tldr here is that the major versions of server and frontend would be compatible but using different major versions of server and frontend would not guarantee compatibility.  For example HospitalRun frontend 1.x would be compatible with HospitalRun server 1.x, but HospitalRun frontend 2.x would not have guaranteed compatibility with HospitalRun server 1.x.  This means that breaking changes would have to wait for major releases.

**Comment by phanimahesh** [comment]
Yes, that sounds good.
