### ISSUE TITLE
Inventory Import needs to be updated to new schema

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-server#47]
Since the move to ember-pouch, https://github.com/HospitalRun/hospitalrun-server/blob/master/utils/inv-import.js does not properly load inventory data.  The script needs to be updated to load the inventory data using the ember-pouch schema, eg:

```js
{
  "_id": "inventory_2_iiqtc6w3_31",
  "_rev": "4-8b68967daca21a66f63837d3900439cb",
  "data": {
    "distributionUnit": "vial",
    "friendlyId": "m00001",
    "inventoryType": "Medication",
    "name": "Cefazolin 500mg vial (Hazolin)",
    "quantity": 999986,
    "lastModified": "2017-04-12T15:30:07.970Z",
    "modifiedBy": "Admin User",
    "purchases": [
      "E3B2184F-4ECA-3B76-92C8-437846C2E3DC"
    ],
    "locations": [
      "24BB235E-B271-AF61-9A3D-9ACD77CE25AF",
      "DBCF3E06-B812-B6C7-930E-74F9372D384A"
    ]
  }
}
```

**Comment by baoqchau** [comment]
hi @jkleinsc. I want to help with this issue. Would you like to help me identify which part of `inv-import.js` should I change to fit with new data using ember-pouch schema? Thanks a lot.

**Comment by KenyanGeek** [comment]
@baoqchau i am really stuck on this issue any help would be appreciated...:-)

**Comment by rwanyoike** [comment]
Hi @jkleinsc :), `ember-pouch` is expecting a CouchDB doc field to be _wrapped_ in a `data` object, something like:

```js
{
    _id: '...',
    _rev: '...', 
    data: {
        aisleLocation: ...,  # <- field inside data object
        currentQuantity: ...,  # <- field inside data object
        ...
    }
}
````

but `inv-import.js` is generating CouchDB docs **without** this data object, something like:

```js
{
    _id: '...', 
    _rev: '...', 
    aisleLocation: ..., # <- not inside data object
    currentQuantity: ...,  # <- not inside data object
    ...
}
```

What you're looking for are functions inside of `inv-import.js` (e.g [`addPurchase`](https://github.com/HospitalRun/hospitalrun-server/blob/524eaa8850170ccee99142614d8d47354386870f/utils/inv-import.js#L74-L86)) where docs are being generated.

**Comment by tangollama** [comment]
@rwanyoike would you have interest in working on this?

**Comment by rwanyoike** [comment]
@tangollama #67 until a better solution comes along...
