### ISSUE TITLE
Correct Docker install scripts

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-server#48]
The Docker install instructions have a bad syntax.  It appears as: 
   git clone git@github.com:HospitalRun/hospitalrun-server.git

It Should Be:
git clone https://github.com/HospitalRun/hospitalrun-server.git

(installing on Ubuntu 16.04 server)

**Comment by tangollama** [comment]
The command in the scripts works for me. Was it malfunctioning for you? If so, what's the error?

**Comment by garylm** [comment]
Joel, no error.  As I said, it is completely working before rebooting the server.  Then Docker is running but none of the images have been started up.  It is like there is a startup script to be run on reboot.

Thanks,

Gary
Gary Miller
gary@groupmiller.com<mailto:gary@groupmiller.com>

**Comment by garylm** [comment]
See #52 for solution
