### ISSUE TITLE
Docker install instructions need a line regarding "docker-compose up -d" on startup of the server.

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-server#54]
"Run "docker-compose up -d" on startup of the server." needs to be added to the Docker server install discussion at https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md

**Comment by jkleinsc** [comment]
@garylm it appears to be already documented as step 4 here:
https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md#step-by-step-guide

Or am I misunderstanding what you are asking?  If so, can you clarify what you think needs to added where?

**Comment by garylm** [comment]
It requires adding a script on reboot that runs "docker-compose up -d" .  Happily I just updated to the latest github hospitalrun-server that you just fixed & it now "mostly" works.   The 8055 and 443/80 port services are now working.

**Comment by garylm** [comment]
Couchdb management service still does not run.   localhost:5985 yields "{"couchdb":"Welcome"... version, etc.   Port 5984 has no response.

**Comment by garylm** [comment]
BTW: It is still the case that based upon the install, after rebooting, only Docker is running.  "docker ps" yields a blank table.   That is why I have to run "docker-compose up -d"

**Comment by jkleinsc** [comment]
@garylm I get what you are saying now.  I think docker-compose.yml could be changed to automatically run the containers on restart but it currently doesn't do this.  This document describes the restart parameter that can be used: https://docs.docker.com/compose/compose-file/#deploy

**Comment by tangollama** [comment]
@garylm same question here? :)
