### ISSUE TITLE
Docker YML host name not working with format "owh.mydomain.com"

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-server#55]
HR runs fine locally in a browser on the server as http://localhost:8055.  BUT will not run as http://owh.mydomain.com.  This is the domain name specified in the yml file.

**Comment by jkleinsc** [comment]
@garylm The docker container sets up your domain as https, so you would have to access as https://owh.mydomain.com or if you wanted http,  http://owh.mydomain.com:8055

**Comment by garylm** [comment]
Remote access worked fine as soon as I got your Docker update in place.  Since I do not have IT privileges at OWH I took the short cut of adding to my personal domain as owh.groupmiller.com.
AGAIN THANKS I probably banged my head against this for 20+ hours before starting to yell at HR folks.
