### ISSUE TITLE
Docker Server - No access to CouchDB

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-server#56]
With the Docker server install on Ubuntu Server, there is no port 5984 couchdb service running.  Thus no way to manage the database.  However, HR is allowing me to enter patients and change lists.

**Comment by jkleinsc** [comment]
@garylm looking at the Docker setup, I think couchdb is mapped to port 5985:
https://github.com/HospitalRun/hospitalrun-server/blob/master/docker-compose.yml#L38

**Comment by jkleinsc** [comment]
@garylm I just verified this.  Go to localhost:5985 when using Docker to access CouchDB

**Comment by garylm** [comment]
Works after your script update and being reminded about "_util"
