### ISSUE TITLE
Optimizing Production Deployment

### ISSUE THREAD

**Issue by lalluanthoor** [HospitalRun/hospitalrun-server#57]
Hi team,

I was searching through the GitHub when I came across this project. As a developer working in Healthcare field, I would like to contribute to the project as well.

These are some suggestions/questions that came to my mind after a quick look through the repository.

- The NodeJS part is scattered across the repository. It could be moved to a single folder along with the `Dockerfile`. This will result is separate folders for each of the components required for `docker-compose`.
- The base image used for the NodeJS part is `node:boron` and the build is done inside the container. Although this simplifies the build process, it makes the image heavy. `node:boron-slim` image is less than half the size of the current image and provides the same functionality. `curl` also comes in-built.
- Further optimizations are possible in `Dockerfile` code, and further more if we put all the NodeJS code in one folder. For example, separate `mkdir` command is not required.
- The only parameter required to be edited before running the application is the `DOMAIN_NAME` parameter in `docker-compose.yml`. This also means that we can supply the built Docker images over Docker Hub, and refer them in the `docker-compose.yml` rather than building them everytime. This will ensure that the software can be deployed with consistent dependencies. This could be added as an option for people who wish to deploy it direclty into production.
- The documentation seems to be lacking descriptions for some of the entries (such as the key files).

And out of curiosity, few more question.
- Is there any plans of supporting deployment on [Kubernetes](https://kubernetes.io/) or [Docker Swarm](https://docs.docker.com/engine/swarm/)?
- Is there already a CI-CD pipeline setup for this repository? I could see a `.travis.yml` but no build status embedded in the README. Also couldn't find anything on [Travis Portal](https://travis-ci.org/HospitalRun).

Regards<br>
Lallu

**Comment by jkleinsc** [comment]
@lalluanthoor thanks for your interest in this project.  If you would like to contribute a PR with Docker improvements that would be gladly welcomed!

As far as Kubernetes or Docker Swarm, we currently don't have anyone involved in the project who has experience in those environments, but we would love to eventually support more deployment options.

We do not currently have a a CI-CD pipeline setup.  I think some work may have started on that but it was never finished.

**Comment by lalluanthoor** [comment]
@jkleinsc I have already submitted a PR #59  for the first part of my questions.

For the second part, I was going through how to setup automated Docker image builds out of a Github repository. Docker Hub already provides [this feature](https://docs.docker.com/docker-hub/github/). But for this to work, we might need to split the repository into multiple repositories, with each one producing a single Docker image.

For the third part, only some minor adjustments in the `docker-compose.yml` and a separate deployment guide would be required to deploy the server on a Docker Swarm.

What are  your thoughts?

**Comment by jkleinsc** [comment]
@lalluanthoor I think setting up automated Docker image builds would be great.  If I understand it properly, I think we would need three repos:
1 - HospitalRun -- probably use this repo (hospitalrun-server)
2 - HospitalRun logstash
3 - HospitalRun nginx

It looks like the couchdb and elasticsearch containers are prebuilt containers.

**Comment by lalluanthoor** [comment]
@jkleinsc 

### Proposal

#### Assumptions
 - It is OK to store default credentials in source code.

#### Decomposition of Current Repository
 - hospitalrun-server
   - `conf` folder
   - `patientimages` folder? I don't know why this folder is there.
   - `utils` folder
   - `.dockerignore`
   - `.eslintignore`
   - `Dockerfile`
   - `app.js`
   - `config-example.js`
   - `package.json`
 - hospitalrun-logstash
   - `logstash` folder
 - hospitalrun-nginx
   - `nginx` folder
 - hospitalrun
   - `docker-compose.yml`
   - `DEPLOYMENT_GUIDE.md`

The `CODE_OF_CONDUCT.md`, `README.md`, `LICENSE`, `.gitignore`, etc. should be there in all the repos.

The other two containers (elasticsearch and couchdb) are pre-built and we only use them as is. I also checked with the elastic team whether they have a thinner version of these images. They currently do not have any. Their recommendation was to use the open source code base directly and optimize it to our needs. Currently, we can put it as out of scope for this discussion.

#### Why Four and not Three
 - all the images get their own repositories, clear separation, easy to manage
 - releases can be made using only updating the image versions in `docker-compose.yml`, clean and independent of work in other repos
 - only require minimal cloning (few files and their history), easy for deployment, no build environment needed in customer side (`node`, `npm`)
 - customisation of images are easy as well; customer can pull any of our shipped images, make necessary changes, and update the `docker-compose.yml` to use the custom image

**Comment by jkleinsc** [comment]
@lalluanthoor looks good to me.

As far as patientimages, it is a directory that needs to exist for the server (patient photos are saved here); Also there should be an `/attachments` directory.  They need to exist in the running container.

**Comment by lalluanthoor** [comment]
@jkleinsc I need some clarifications.

- The `patientimages` and `attachments` are part of which server? Node or Nginx?
- Are they located in the site root or file system root?

**Comment by jkleinsc** [comment]
@lalluanthoor `patientimages` and `attachments` are part of the Node server.  It needs to be able to write to those directories and serve files from those directories.  They are located at site root, dictated by the value set in config.js (defaults to patientimages and attachments under the node app root directory).

**Comment by lalluanthoor** [comment]
@jkleinsc thank you. Could you also create the empty repos? I don't have write access.

**Comment by jkleinsc** [comment]
@lalluanthoor I created the repos.  For the "hospitalrun" one, use hospitalrun-deploy.

**Comment by lalluanthoor** [comment]
#### PR Updates
1. The NodeJS components remain in the [current repository](https://github.com/HospitalRun/hospitalrun-server/).
1. The Nginx component moved to it's [own repository](https://github.com/HospitalRun/hospitalrun-nginx/).
1. The LogStash component moved to it's [own repository](https://github.com/HospitalRun/hospitalrun-logstash/).
1. The Docker Compose component moved to it's [own repository](https://github.com/HospitalRun/hospitalrun-deploy/).
1. Tagged all 4 repositories with `1.0.0-beta2`.

#### Docker Hub Updates
1. @jkleinsc and myself have setup automatic build for the containers whenever a new tag is pushed to Github.
1. The tag should match the regex `/^\d+\.\d+\.\d+(-[a-z]+(\d+)?)?$/`. It will match regular SemVers (like 1.0.0, 1.1.1, etc) as well as pre-releases (like 1.0.0-beta, 1.0.0-beta2, etc).
1. The images will be qualified with the same tag.
1. The NodeJS server image can be found at [hospitalrun/hospitalrun-server](https://hub.docker.com/r/hospitalrun/hospitalrun-server/).
1. The LogStash server image can be found at [hospitalrun/hospitalrun-logstash](https://hub.docker.com/r/hospitalrun/hospitalrun-logstash/).
1. The Nginx server image can be found at [hospitalrun/hospitalrun-nginx](https://hub.docker.com/r/hospitalrun/hospitalrun-nginx/).

Please refer to the linked PRs for code changes.

Notifying @jkleinsc @tangollama @mofesola @jglovier

**Comment by lalluanthoor** [comment]
@jkleinsc Is there any specific reason why the logstash configuration is loaded during runtime rather than adding it to the image directly? If not, I would like to make it part of the image build process and remove the volume mounting from the `docker-compose.yml`.

**Comment by lalluanthoor** [comment]
I have also closed three of the PRs for safety.

**Comment by jkleinsc** [comment]
@lalluanthoor I'm not sure.  I can't think of why it would need to be done one way vs the other.  @mofesola might be able to explain why it was built that way.
