### ISSUE TITLE
Git Clone AUthentication Issues

### ISSUE THREAD

**Issue by Paredo** [HospitalRun/hospitalrun-server#61]
I try to clone the repository and i keep getting this Below 

git clone git@github.com:HospitalRun/hospitalrun-server.git
Cloning into 'hospitalrun-server'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
sh-3.2#

**Comment by lalluanthoor** [comment]
Try to fork the repo to your account and then cloning it. Only HospitalRun admins will have ssh access to the original repo.

If you want to clone the repo for trying it out, use the https url.

**Comment by tangollama** [comment]
Thanks @lalluanthoor for replying. Unless there's a specific documentation issue here to resolve, closing.
