### ISSUE TITLE
Data import Challenges

### ISSUE THREAD

**Issue by KenyanGeek** [HospitalRun/hospitalrun-server#66]
I have been trying to import data and have hit snags  in the following areas: 

Inventory: There was an issue out there on using utils script to import data. Anybody managed to import an inventory list?

Labs and Imaging: The "backend" meant to update the lab and imaging procedures is "broken."i.e. There is no upload button on the look up list on these as well as ways to adjust the type as is provided in procedures and wards. Anybody managed to do this without having to do it manually from the frontend?

LoadDB: How can we use this  to import a extensive patient list and other lists  in HR? Basically how is it meant to work? Importing a csv leads to errors.

**Comment by drakemedic** [comment]
I agree, the system for adding lab types seems to be broken. It was working in previous installations.

**Comment by donaldwasserman** [comment]
@KenyanGeek @drakemedic Can you connect with me on slack so I can take a look at some of data you're looking at using to see how we can resolve this issue?
