### ISSUE TITLE
Production Environment Gives 502 Gateway Error

### ISSUE THREAD

**Issue by seyyah** [HospitalRun/hospitalrun-server#68]
I created the Docker 17.06.0-ce on 16.04 Droplet and composed hospitalrun-server docker container. I done DNS config, installed nginx and configured ufw.

I follow the [Step-by-Step Guide](https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md) to deploy.

My dockers are healthy,

```sh
docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
53704c8cba8d        hospitalrun_nginx      "/bin/sh -c /etc/n..."   2 hours ago         Up 2 hours          80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8055->8080/tcp   hospitalrunserver_nginx_1
ea3888970ac8        hospitalrun            "/bin/sh -c ./entr..."   2 hours ago         Up 2 hours          3000/tcp                                               hospitalrun
fd8ad7612a5c        hospitalrun_logstash   "/usr/local/bin/do..."   15 hours ago        Up 2 hours          5044/tcp, 9600/tcp                                     logstash_hr
e837f6ba143e        couchdb:1.6            "tini -- /docker-e..."   15 hours ago        Up 2 hours          0.0.0.0:5985->5984/tcp                                 couchdb_hr
```

`netstat` command's output is,

```sh
$ netstat -plutn 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      17601/nginx -g daem
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1368/sshd       
tcp6       0      0 :::80                   :::*                    LISTEN      17601/nginx -g daem
tcp6       0      0 :::22                   :::*                    LISTEN      1368/sshd       
tcp6       0      0 :::8055                 :::*                    LISTEN      4012/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      4031/docker-proxy
tcp6       0      0 :::5985                 :::*                    LISTEN      3364/docker-proxy
```

My droplet' nginx configuration file is,

```sh
worker_processes 1;

events { worker_connections 1024; }

http {
    upstream website {
        server 172.18.0.6:8055;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;
        #server_name 185.14.187.134 app.bulut.dental;
        server_name app.bulut.dental;

        gzip_types text/plain text/css application/json application/x-javascript
                   text/xml application/xml application/xml+rss text/javascript;

        location / {
            proxy_pass http://website;
            #include /etc/nginx/proxy_params;
            #include /etc/nginx/mime.types;
        }
    }
}
```

Each http://185.14.187.134 and http://app.bulut.dental are produced the 502 gateway error. My nginx error' part is,

```sh
2017/08/16 13:06:32 [error] 17602#17602: *9 connect() failed
(111: Connection refused) while connecting to upstream, 
client: 162.158.111.xx, server: app.bulut.dental,
request: "GET / HTTP/1.1", upstream: "http://172.18.0.6:8055/",
host: "app.bulut.dental"
```

I'm not sure whether or not i install the hospitalrun-frontend. I tested successfully hospitalrun-server in local machine but i get error in my droplet.

Can you offer any guide or tutorial for production environment (specifically docker)? Thanks for your time and interest

Rel: https://www.digitalocean.com/community/questions/nginx-502-gateway-error-with-docker

**Comment by garylm** [comment]
My approach was slightly different in that the Digital Ocean instance was intended as a quasi production server.  It is being used for data setup and training by folks in the US and Africa.
- Ubuntu 16.04 Server with all apt-get updates.
- Docker insalled
- HR+ Server version installed by following the directions at -
https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md

- *** Changed the server Domain Name in the Docker-compose.yml file to a valid, tested DNS setting at my domain registrar.  (I am guessing that nginx may have errors if the domain cannot be resolved).

- set up a Digital Ocean Firewall in front of the server to block most ports, rather than using a Linux firewall.  (easier to administer).
My plan is to make/test all code changes on my laptop Docker & push then to the server.

**Comment by seyyah** [comment]
Thank you @garylm reply and help.

The path we are following to deploy is slightly different from ours

1. Firstly, you select Ubuntu droplet from DigitalOcean
2. then apt-get update
3. Install docker
4. Follow the [instructions](https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md)

Our approach is

1. Firstly, we select Docker 17.06.0-ce on 16.04 Droplet (docker installed ubuntu droplet)
2. then apt-get update
3. Follow the [instructions](https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md)

I suspect the Nginx settings are incorrect. Can you share your Nginx settings if you can? I doubt the firewall settings if there is a low possibility. Which ports did you allow?

Thank you for your time and suggestion.

**Comment by seyyah** [comment]
We have solved this problem with mo1.

```sh
$ uname -a
Linux HospitalRun 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -r
Release:	16.04

$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install linux-image-extra-$(uname -r) \
    linux-image-extra-virtual
$ sudo apt-get install apt-transport-https ca-certificates curl \
    software-properties-common
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
$ sudo apt-key fingerprint 0EBFCD88
$ sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
$ sudo apt-get update
$ apt-cache madison docker-ce
$ sudo apt-get install docker-ce=17.09.0~ce-0~ubuntu
$ sudo docker run hello-world
$ sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname  -s`-`uname -m` -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
```

```sh
$ mkdir works
$ cd works
$ git clone git@github.com:HospitalRun/hospitalrun-server.git
$ cd hospitalrun-server/
$ vim docker-compose.yml
# DOMAIN_NAME: example.com
$ sudo docker-compose up --build -d
```
