### ISSUE TITLE
Please consider Postgres as a DB alternative

### ISSUE THREAD

**Issue by mariusa** [HospitalRun/hospitalrun-server#70]
Using a standard SQL database, backed by many enterprises, would help a little in convincing potential customers to consider switching to HospitalRun.
Also, standard existing tools would work too, no need to write custom scripts to export/import CSV.

Thanks

**Comment by tangollama** [comment]
Thanks for the feedback. We chose a document database due to the offline first objectives. If others see value in porting the interface a relational model, that's a worthy exercise; but it's not the focus of this project.
