### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Bikraji** [HospitalRun/hospitalrun-server#82]
Hi, I am experiencing serious performance lack in Hospital Run.
Specifically client side, the browser just hangs.
I think its due to PuchDb, any pointers or improvement suggestions will be greatly appreciated.

**Comment by chaitanya-y** [comment]
hii Bikraji,
i am trying to create patient list but i am getting unauthorized you are not authorized to access this db how tom fix this?

**Comment by p-mcgowan** [comment]
@chaitanya-y your issue is unrelated (see [your actual issue](https://github.com/HospitalRun/hospitalrun-server/issues/139)) - try to keep conversations within issues to the actual stated issue
