### ISSUE TITLE
Accessing HospitalRun through lan computers

### ISSUE THREAD

**Issue by openmrsegypt** [HospitalRun/hospitalrun-server#84]
I recently installed hospitalrun on ubuntu 16 using docker

i want lan computers connected to same network to access the HospitalRun

**Comment by openmrsegypt** [comment]
@tangollama can you please help

**Comment by openmrsegypt** [comment]
can anyone please reply 
what the hell is this !!!!

**Comment by p-mcgowan** [comment]
Hey @openmrsegypt, I'm not associated with the project but I'm sure the maintainers are busy with family over the holidays.

I had no problems connecting to my HR server (ubuntu 16.04 and 17.04) from LAN. I was not running docker but hosting it locally instead, so if you're running it in a container then maybe check docker docs for lan setup instructions.

It might help if you list the steps you took to set it up, how you're trying to connect, and the exact issues/errors when trying to connect locally.

**Comment by openmrsegypt** [comment]
how can i install it without docket
it seems i am not able to understand docket networking

**Comment by p-mcgowan** [comment]
Follow the alternative instructions here
https://github.com/HospitalRun/hospitalrun-server/blob/master/README.md#alternative-installation
You basically just need to serve the files after downloading stuff like couch and elastic search.
If you are only trying to connect locally then you don't need to host anywhere, you should be able to connect to LAN assuming you have forwarded the appropriate ports on your network.

**Comment by openmrsegypt** [comment]
can you please provide clear instructions on how to install couchdb 1.6

it is unavailable in couchdb website version 2.x are the only available

sorry for bothering you

**Comment by p-mcgowan** [comment]
No problem. If you're on Ubuntu, `sudo apt-get install couchdb` will install 1.6.1 (if I recall correctly) since Ubuntu packages are not up to date with the newest couch. If that installs couch 2.x, the  you will need to do `sudo apt-get install couchdb=1.6.1-4ubuntu-something-I-cant-remember`. This link has examples https://askubuntu.com/questions/428772/how-to-install-specific-version-of-some-package/428778

**Comment by openmrsegypt** [comment]
> If you are on Linux distribution that uses Upstart, there is an upstart script in utils/hospitalrun.conf. By default this script assumes the server is installed at /var/app/server. This script relies on forever which you will need to install via npm: npm install -g forever


how to run the hospital run server forever

**Comment by openmrsegypt** [comment]
![screenshot from 2018-01-04 13-35-31](https://user-images.githubusercontent.com/34840635/34561755-382143f2-f154-11e7-84c6-24ed57c701be.png)
@p-mcgowan 
i installed logstash and elastic seearch and all other commands 

i get stuck on searching

**Comment by openmrsegypt** [comment]
+
another problem 
when accessing the site from lan i get stuck on login after i enter the username and password

**Comment by openmrsegypt** [comment]
due ti multiple issues .
i will try to install it via panamx and see how it goes

**Comment by p-mcgowan** [comment]
You could mpve this to the slack channel, as it sounds closer to IT issues rather than codebase issues, and more people may be able to help you there if you still have issues. Thr link to the slack is on the hospitalrun website

**Comment by jwamoo** [comment]
I have been trying to get install HospitalRun on Ubuntu 14.04.
Followed the alternative instruction till I got to IV

IV. Setup CouchDB for HospitalRun:
   a. Download https://github.com/HospitalRun/hospitalrun-frontend/blob/master/script/initcouch.sh
   b. If you have just installed CouchDB and have no admin user, simply run initcouch.sh with no
       arguements. A user hradmin will be created with password: test.
    c. If you already have a CouchDB admin user, please run initcouch.sh USER PASS. USER and PASS are 
        the CouchDB admin user credentials.

Tried running inticouch.sh but had an error that reads 
line 1: syntax error near unexpected token '<'
line 1: <'htmk>body>You are being <a href="https://github/HospitalRun/hospitalrun-frontend/blob/master/script/intcouch.sh">redirected</a>.</body></html>'

I'm stuck!

**Comment by p-mcgowan** [comment]
Not sure, but you might try downloading the script that the redirection notice points you to in your error above.  
=> https://github/HospitalRun/hospitalrun-frontend/blob/master/script/intcouch.sh
